### ISSUE TITLE
Wrong URL for init.sh script

### ISSUE THREAD

**Issue by theluke** [draios/instruqt-assets#14]
Hi,

the correct **US-West** URL for checking the agent key is [https://us2.app.sysdig.com/#/settings/agentInstallation](https://us2.app.sysdig.com/#/settings/agentInstallation).
Currently the URL displayed is [[https://app.sysdigcloud.com/#/login](https://app.sysdigcloud.com/#/login)](https://app.sysdigcloud.com/#/login)
Thank you!

**Comment by pmusa** [comment]
@theluke There is something wrong with the URLs you posted. Can you paste the complete URL that is printed by the script and put below the complete correct URL? Thank you
