### ISSUE TITLE
Agent connected to the wrong region

### ISSUE THREAD

**Issue by theluke** [draios/instruqt-assets#17]
Hey folks,
running [this track](https://play.instruqt.com/sysdig/tracks/tmp-capture-forensics), in the second challenge, the agent installation script is giving me this error:

```
Configuring Sysdig Agent
  Visit https://us2.app.sysdig.com/#/settings/agentInstallation to retrieve your Sysdig Agent Key.
  Insert your Sysdig Agent Key: b7cceb56-11b0-4527-b4a6-bbdedae883ad
  The agent is being installed in the background.

  Testing if Sysdig Agent is running correctly...
/root/prepare-track/init.sh: line 329: [: missing `]'
  FAIL
  Agent connected to wrong region.
    Selected collector: ingest-us2.app.sysdig.com
    Found collector: ingest-us2.app.sysdig.com

```

**Comment by pabloopez** [comment]
the second challenge should not run the init.sh. Was it run on the first step?

**Comment by theluke** [comment]
> the second challenge should not run the init.sh. Was it run on the first step?

My bad, I edited the text of the issue.
In the second challenge I am installing the agent.

**Comment by pmusa** [comment]
https://sysdigcloud.slack.com/archives/GPW3T4T7V/p1639504464006900
