### ISSUE TITLE
Change Sysdig Agent tagging in init.sh

### ISSUE THREAD

**Issue by theluke** [draios/instruqt-assets#26]
I hereby propose to update the agent tagging criteria to something more meaningful than `insq_date_time`.

A possible alternative would be: `training_yyyy-mm-dd`.

The agent tagging is executed here:
https://github.com/draios/instruqt-assets/blob/0416debbb6814bc21cba351be53bf5d4f635f69e/common/prepare-track/install_with_helm.sh#L39
and here:
https://github.com/draios/instruqt-assets/blob/0416debbb6814bc21cba351be53bf5d4f635f69e/common/prepare-track/init.sh#L285

**Comment by theluke** [comment]
@Jujuyeh @pabloopez what do you think guys?

**Comment by pabloopez** [comment]
LGTM, the instruqt string is only relevant for us. I would even go further for something date-time only like:

`$(date -d '+2 hour' +"%F__%H_%M") `

**Comment by pabloopez** [comment]
in most of cases it is easy to discern what's the cluster that we are seeing data coming from in Sysdig Monitor, but I would also like to see a file with the `${CLUSTER_NAME}` value inside. Same location where we store other data and flags.

**Comment by theluke** [comment]
Thank you @pabloopez .
My feedback comes from the learner standpoint, I would not use just the date, instead `training + date` would be better.
As for your second comment, I did not understand it ... sorry mate. Can you please clarify?

**Comment by pabloopez** [comment]
NP @theluke . Your feedback is welcomed, no need to justify you providing it. 

The reason for the `insq_` appendix was to keep it sort and easy to see the full clusterName in some fields (Explore, for example, or other menus were you have to select and compare between different cluster). The idea is to keep it short to show all the relevant info, specially time.

Second comment: I am suggesting to get the content of `${CLUSTER_NAME}` printed to a file that we can check. Nothing critical, just an small add-on.
